name: Playwright Enterprise Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:

  test:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Ensure storage directory
        run: mkdir -p storage

      - name: Run Playwright tests
        run: pnpm exec playwright test --shard=${{ matrix.shard }}/2
        env:
          CI: true
          BASE_URL: https://www.saucedemo.com
          USERNAME: standard_user
          PASSWORD: secret_sauce

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-shard-${{ matrix.shard }}
          path: allure-results/
          retention-days: 7


  allure-report:
    name: Allure Report (Merged)
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile

      - name: Download Shard 1
        uses: actions/download-artifact@v4
        with:
          name: allure-results-shard-1
          path: allure-results-merged

      - name: Download Shard 2
        uses: actions/download-artifact@v4
        with:
          name: allure-results-shard-2
          path: allure-results-merged

      - name: Generate Allure Report
        run: pnpm exec allure generate allure-results-merged --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/